---
- name: Configure Azure VM for Ansible Lab
  hosts: azure_vm
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  
    - name: Install required packages
      apt:
        name: apache2
        state: present

    - name: Start Apache and enable it on boot
      service:
        name: apache2
        state: started
        enabled: yes
  
    - name: Create a directory in hostname
      file:
        path: /home/azureuser/ansible_lab
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Deploy custom index.html
      copy:
        content: "<html><body><h1>Welcome to Ansible Lab on azure</h1></body></html>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'